### PR TITLE
Updated gradle and libraries to latest versions.

### PR DESCRIPTION
**Pull request by applebyter**
I have updated gradle to 7.5, and all of the libraries used by the game engine to their latest versions. I've also tried to get gradle to enforce the use of Java 17 for building and testing of the game engine.

### CODE REVIEW

**Review by Jonoym — APPROVED** [review]
It is working on Windows OS after updating my Java Environment Variable to JDK17. The JDK version set was previously commented out possibly due to similar issues. Students may have similar issues but it can be easily fixed.

The only issues caused by not updating the Java Environment Variable is that the game does not launch using Gradle but can be launched through IntelliJ without issues.

**Comment by samantha-tran** [comment]
Works on mac. However had to add "-XstartOnFirstThread" to jvmArgs list as referenced [here](https://github.com/UQdeco2800/game-engine/wiki/MacOS-Setup-Guide)

**Review by samantha-tran — APPROVED** [review]

**Review by BozenX — APPROVED** [review]
After installing Java 17 manually, game works on mac with -XstartOnFirstThread argument added. Java 17 didn't seem to install from the toolchain.

**Comment by applebyter** [comment]
Agreed to move game engine to Java 17.

**Pull request merged**
